### PR TITLE
LPS-98472 add @JSON annotation to boolean getter

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-98472

Adding annotation as per https://github.com/brianchandotcom/liferay-portal/pull/40070/commits/7b5d5b6df88557f08c999098031144282a4d48b2. Should we also be sending to 7.1.x?

### CODE REVIEW

**Comment by holatuwol** [comment]
@ryannealeigh : Does the fix still work if we remove the existing `@JSON` annotation on the `getField2` method?

**Comment by holatuwol** [comment]
@ryannealeigh : I checked, and the 7.1.x is similar to the master branch, in that it doesn't exist in liferay/liferay-plugins and liferay/liferay-plugins-ee.

**Comment by ryannealeigh** [comment]
@holatuwol : I didn't test removing the removing from `getField2`. But I can move forward and do that if necessary. I checked as well just now and noticed the same situation with the 7.1.x branch.

**Comment by holatuwol** [comment]
@ryannealeigh: Never mind, from the commit message, I was under the impression that we only annotated one method, but checking a real example (`UserModelImpl`), I see that was not the case.

**Comment by holatuwol** [comment]
https://github.com/brianchandotcom/liferay-plugins/pull/5438

**Comment by holatuwol** [comment]
https://github.com/brianchandotcom/liferay-plugins/pull/5439

**Pull request closed without merging**
